name: clang-tidy-review

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: "clang install"
      run: |
        sudo apt update && \
        sudo apt install -y clang clang-tidy
    - name: "generate compile_commands.json"
      run: |
        mkdir build && cd build && \
        cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON .. && cd ..
    - name: "clang-tidy"
      run: |
        find ${{ github.workspace }} -iname *.h -o -iname "*.cpp" | xargs clang-tidy -p=./build